# Use the official Node.js 16 image as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json into the container
COPY ./frontendRunEnv/package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally for development
RUN npm install -g nodemon

# Copy the rest of the application code into the container
COPY ./frontendRunEnv .

# Expose the port the app runs on
EXPOSE 5173

# Command to run nodemon
CMD ["npm", "start"]
